import os
import sys
import json
import urllib.request
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

def send_to_slack(json_file_path):
    """
    Reads the agnostic JSON payload generated by the AI Core
    and transforms it into Slack Block Kit UI format.
    """
    webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
    if not webhook_url:
        print("Error: SLACK_WEBHOOK_URL is not set in .env")
        sys.exit(1)

    try:
        with open(json_file_path, 'r') as f:
            data = json.load(f)
    except Exception as e:
        print(f"Error reading JSON file: {e}")
        sys.exit(1)

    # Build Slack Blocks
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🌅 Daily Briefing: {data.get('date', 'Today')}",
                "emoji": True
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": data.get('intro_text', 'Here is your daily update.')
            }
        },
        {"type": "divider"}
    ]

    # Process Action Items
    action_items = data.get('action_items', [])
    if action_items:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": "*🔴 ACTION REQUIRED*"}
        })
        for item in action_items:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*{item.get('title')}* `[{item.get('pill_text')}]`\n{item.get('description')}"
                }
            })
        blocks.append({"type": "divider"})

    # Send Request
    payload = {"blocks": blocks}
    req = urllib.request.Request(
        webhook_url, 
        data=json.dumps(payload).encode('utf-8'), 
        headers={'Content-Type': 'application/json'}
    )

    try:
        response = urllib.request.urlopen(req)
        if response.status == 200:
            print("Successfully sent Daily Update to Slack!")
        else:
            print(f"Failed to send to Slack. Status Code: {response.status}")
    except Exception as e:
        print(f"HTTP Request failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 slack_adapter.py <path_to_json>")
        sys.exit(1)
    
    send_to_slack(sys.argv[1])